set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS25} [get_ports eth_mdc]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS25} [get_ports eth_mdio]

set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS25} [get_ports net_tx_ctl]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS25} [get_ports net_txc]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS25} [get_ports {net_txd[0]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS25} [get_ports {net_txd[1]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS25} [get_ports {net_txd[2]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS25} [get_ports {net_txd[3]}]

set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS25} [get_ports net_rx_ctl]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS25} [get_ports net_rxc]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS25} [get_ports {net_rxd[0]}]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS25} [get_ports {net_rxd[1]}]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS25} [get_ports {net_rxd[2]}]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS25} [get_ports {net_rxd[3]}]

create_clock -period 8.000 -name eth_rxc [get_ports net_rxc]

set_property SLEW FAST [get_ports net_tx_ctl]
set_property SLEW FAST [get_ports net_txc]
set_property SLEW FAST [get_ports {net_txd[*]}]

# access built in GPS receiver
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS25} [get_ports GPS_nRESET]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS25} [get_ports GPS_UART_TXD]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS25} [get_ports GPS_UART_RXD]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS25} [get_ports GPS_PPS]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets GPS_PPS_IBUF]



# constraints (pzsdr1.b)
# ad9361
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_p]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_n]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_p]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_n]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[0]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[0]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[1]}]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[1]}]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[2]}]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[2]}]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[3]}]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[3]}]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[4]}]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[4]}]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[5]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[5]}]

set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVDS_25} [get_ports tx_clk_out_p]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVDS_25} [get_ports tx_clk_out_n]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVDS_25} [get_ports tx_frame_out_p]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVDS_25} [get_ports tx_frame_out_n]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[0]}]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[0]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[1]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[1]}]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[2]}]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[2]}]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[3]}]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[3]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[4]}]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[4]}]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[5]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[5]}]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl[0]}]
set_property -dict {PACKAGE_PIN Y6 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl[1]}]
set_property -dict {PACKAGE_PIN Y7 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl[2]}]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl[3]}]
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS25} [get_ports {gpio_status[0]}]
set_property -dict {PACKAGE_PIN W10 IOSTANDARD LVCMOS25} [get_ports {gpio_status[1]}]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVCMOS25} [get_ports {gpio_status[2]}]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS25} [get_ports {gpio_status[3]}]
set_property -dict {PACKAGE_PIN W8 IOSTANDARD LVCMOS25} [get_ports {gpio_status[4]}]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD LVCMOS25} [get_ports {gpio_status[5]}]
set_property -dict {PACKAGE_PIN U10 IOSTANDARD LVCMOS25} [get_ports {gpio_status[6]}]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS25} [get_ports {gpio_status[7]}]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS25} [get_ports gpio_en_agc]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS25} [get_ports gpio_resetb]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS25} [get_ports txnrx]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS25} [get_ports enable]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS25} [get_ports gpio_sync]

set_property PACKAGE_PIN T10 [get_ports spi_csn]
set_property IOSTANDARD LVCMOS25 [get_ports spi_csn]
set_property PULLUP true [get_ports spi_csn]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS25} [get_ports spi_clk]
set_property -dict {PACKAGE_PIN T12 IOSTANDARD LVCMOS25} [get_ports spi_mosi]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS25} [get_ports spi_miso]


set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS25} [get_ports TRX1_nTX_RX]
set_property -dict {PACKAGE_PIN W11 IOSTANDARD LVCMOS25} [get_ports RX1_TRX_nRX]
set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVCMOS25} [get_ports RX2_nTRX_RX]
set_property -dict {PACKAGE_PIN V6 IOSTANDARD LVCMOS25} [get_ports TRX2_TX_nRX]

# clocks

create_clock -period 8.000 -name rx_clk [get_ports rx_clk_in_p]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list i_system_wrapper/system_i/util_ad9361_divclk/inst/clk_out]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {i_system_wrapper/system_i/magnitude_approx_0_magnitude[0]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[1]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[2]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[3]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[4]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[5]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[6]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[7]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[8]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[9]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[10]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[11]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[12]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[13]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[14]} {i_system_wrapper/system_i/magnitude_approx_0_magnitude[15]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out]
